spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:security_prac
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug